### PR TITLE
update package information

### PR DESCRIPTION
**Pull request by andrewrk**
Hello. Yet another packaging pull request... This saves me from having to manually update copyright information.

### CODE REVIEW

**Comment by rvagg** [comment]
what's the main purpose of this? there's two author entries in there now, perhaps just the `"authors"` should have been renamed to `"author"` if that's what you were aiming for

**Comment by andrewrk** [comment]
Hmm good question. I just ran `npm init` on package.json actually. I think what this comes down to is that [npm2deb](https://github.com/LeoIannacone/npm2deb) uses the `author` field to pre-populate copyright information. And I've already corrected the package - this pull request is like, well, if this were there before I started it would have saved some time.

I think that's right. Sorry, I'm in the process of trying to package up something like 80 modules right now and it's hard to keep them all straight.

**Comment by rvagg** [comment]
@andrewrk I've fixed up the author field but I want to register my disagreement with what you're doing by putting all of these packages into Debian form. The way node and npm work is fundamentally different to an OS-level package manager because we can _ignore version conflicts_ in almost all cases. It's ok to have two versions of the same package existing in the same dependency tree. This doesn't work if you extract them out of npm and you break one of the best features of Node.

If you're using `apt-get` to install Node packages then you're simply _Doing It Wrong<sup>:tm:</sup>_.

**Comment by andrewrk** [comment]
I understand what you're saying. And you're right. Believe me, I get the beauty of installing multiple versions simultaneously.

However, try to put on my shoes for a second:

```
# apt-get install groovebasin
```

That's it. One step. Everything is solved. Further:

```
$ apt-cache search music player
...
groovebasin - music player server and web-based client
...
```

You have to admit, this is a worthy goal. And what it requires is adhering to Debian's security policy regarding packages: if a bug is fixed in a package one time, then it should fix the bug _everywhere_. I understand why they have that policy. And I'm willing to jump through some hoops to adhere to the policy.

**Comment by ghost** [comment]
Just put `node_modules/` into the .deb package as-is. Boom, problem solved.

**Comment by andrewrk** [comment]
Are you trolling @substack? I think that you're aware of the strict policy against that.

**Comment by juliangruber** [comment]
debian packages are too semantic, code inside `node_modules/` should just be treated as arbitrary code, and not dependencies.

**Comment by andrewrk** [comment]
@juliangruber I understand your frustration. Can you see the other perspective?

**Comment by juliangruber** [comment]
@andrewrk i can and i sympathize with your situation. i think we can find a solution, however it shouldn't require node modules to change. Does it count when you browserify your code and thus only have one javascript file with all the node_modules code?

**Comment by andrewrk** [comment]
> Does it count when you browserify your code and thus only have one javascript file with all the node_modules code?

I think the policy in this situation is that all the build-dependencies have to be Debian packages and the so the generated client-side browserified file will be built from all Debian packages of node modules.

> shouldn't require node modules to change

Please note that all that this particular pull request contains is package.json updated to current conventions (all I did was run `npm init`!) and @rvagg has graciously pulled it into master and published it already. I don't think (in this case at least) I'm asking this node module to go out of its way for Debian.

**Comment by rvagg** [comment]
This time it's easy but to maintain this into the future you're going to have to chase your tail getting everyone to keep versions in sync. I for one would rather _not_ be reminded of the dependency management hell of Java and pitty the job you're going to have to do herding all those cats.

**Pull request closed without merging**
